### ISSUE TITLE
rhub mac fails to compile (Java error)

### ISSUE THREAD

**Issue by antcalcagni** [r-hub/rhub#189]
Hello,
I tried to compile my R package via r-hub builder on MacOs platforms but I get the following error:

`Started by user r-hub Jenkins admin
Building remotely on 192.168.23.10-0bb493a3 (slave mavericks r-oldrel swarm macos) in workspace /Users/rhub/workspace/ssMousetrack_1.1.5.tar.gz-8815cedafb8ebf7447fe6dbbe7b66957
java.io.IOException: Failed to mkdirs: /Users/rhub/workspace/ssMousetrack_1.1.5.tar.gz-8815cedafb8ebf7447fe6dbbe7b66957
	at hudson.FilePath.mkdirs(FilePath.java:1191)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1267)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:604)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:529)
	at hudson.model.Run.execute(Run.java:1741)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)
Pinging https://builder.r-hub.io/build/FAILURE/ssMousetrack_1.1.5.tar.gz-8815cedafb8ebf7447fe6dbbe7b66957/2019-01-13T20:20:10Z
{"status":"ok"}
Finished: FAILURE`

Is it related to the rhub server?

Thanks

**Comment by gaborcsardi** [comment]
I suspect that this is solved now. Please reopen if you still have problems.
