### ISSUE TITLE
PREPERROR on Linux R-devel

### ISSUE THREAD

**Issue by knausb** [r-hub/rhub#338]
Hi, [my package](https://github.com/knausb/vcfR) is currently throwing warnings on CRAN on R-devel. I've used

```
rhub::check(platform = "debian-gcc-devel")
```

and

```
rhub::check(platform = "fedora-gcc-devel")
```

and receive the below output.

```
Started by user r-hub Jenkins admin
Building remotely on 10.2.0.5-ca79fee5 (slave swarm linux) in workspace /home/ubuntu/workspace/vcfR_1.9.0.9000.tar.gz-5ca3732aab624b28995c7e6a603e8b5b
java.io.IOException: Failed to mkdirs: /home/ubuntu/workspace/vcfR_1.9.0.9000.tar.gz-5ca3732aab624b28995c7e6a603e8b5b
	at hudson.FilePath.mkdirs(FilePath.java:1191)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1267)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:604)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:529)
	at hudson.model.Run.execute(Run.java:1741)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)
Pinging https://builder.r-hub.io/build/FAILURE/vcfR_1.9.0.9000.tar.gz-5ca3732aab624b28995c7e6a603e8b5b/2020-02-04T02:20:24Z
{"status":"ok"}
Finished: FAILURE
```

I'm not sure how to interpret this, but I don't think it has to do with my package. There are a few other "PREPERROR" issues here, but I don't think they're the same. Thanks!

**Comment by gaborcsardi** [comment]
This seems like a temporary worker failure, can you just try again? Thanks.

**Comment by knausb** [comment]
On 2020-02-03 I ran three jobs that all failed as reported. This made me believe that this was not temporary. On 2020-02-04 I tried again and it appears this issue has resolved itself. (Still have an error but I believe this is due to my package.) I feel this validates that this was indeed temporary. Thank you!
